### ISSUE TITLE
API secret keys in the public source code

### ISSUE THREAD

**Issue by paul-marty** [promethe42/cocorico#105]
Hello,

It seems that there is your API secret Keys in the source code (FranceConnect, Facebook and Google):
https://github.com/promethe42/cocorico/blob/1f422f4d801a30e75f9a46742a0205e7202ee90c/provisioning/inventory/group_vars/image.yml

Please revoke the secret keys ASAP before bad guys use it.

Paul

**Comment by JMLX42** [comment]
Yep, I know.
But AFAIK, Google and Facebook keys are useless for apps that are not on the right domain. And you can't change the authorized domains without my admin credentials. Isn't that right?
And it's not the case for FranceConnect. But I sent an e-mail to their tech support and they simply don't care...

The problem is we need at least 1 auth method to be set for the local dev config...

Or should we require every developer to provide their own credentials?

**Comment by paul-marty** [comment]
Yep this is correct, so an attacker would also need to find a cross-site scripting vulnerability on the website hosted on the right domain. It is still possible and in any case, the secret key must remain secret to the dev team (It is better if each dev has its own key). 
Git(hub) can remove the keys automatically from source code during the commit process : https://help.github.com/articles/remove-sensitive-data. 

On the long run, it might be interesting to have a look on Oracles for Ethereum (E.g. http://www.oraclize.it). In a perfect world, France Connect would provide its services directly on the blockchain. I sent them a message on twitter and they replied that the access "is not active".

**Comment by JMLX42** [comment]
> Git(hub) can remove the keys automatically from source code during the commit process : 

Sure. But then when you clone/provision the repo, you won't be able to test/dev on the platform because the API keys are missing... How can we solve that?

> On the long run, it might be interesting to have a look on Oracles for Ethereum (E.g. http://www.oraclize.it).

http://dapps.oraclize.it/proof-of-identity/ looks cool. I'll have a closer look.
Still, the Web API <=> blockchain relationship has some very specific constraints regarding performances and reliability. I'm not sure this project can handle that.

Still, the idea behind this could be a good way to break the security/surveillance risk related to FranceConnect. I'll think about it.

> In a perfect world, France Connect would provide its services directly on the blockchain.

I want to boostrap a foundation to fund and manage Cocorico as an open and community driven project.
Having an alternative to FranceConnect or making it blockchain-ready could be a good project for this foundation.

Looks like you want to contribute! :) Maybe you could [join the gitter](https://gitter.im/cocorico-vote/Lobby) so that we can talk!

**Comment by paul-marty** [comment]
> Sure. But then when you clone/provision the repo, you won't be able to test/dev on the platform because the API keys are missing... How can we solve that?

Anyone who wants to run the server app should request its own credentials to api providers. I am not sure that it is possible with France Connect so sharing a single api key between the core dev is already a step forward (use a password manager).

> Still, the idea behind this could be a good way to break the security/surveillance risk related to FranceConnect. I'll think about it.

I fully agree, IMO there is no better security than public blockchain for such political project. 

>Looks like you want to contribute! :) Maybe you could join the gitter so that we can talk!

I will join and try to support you but I don't have much free time.
